<?php

$default_hintlink         = _("Desperate? Can't find it?");
$default_challenge        = _("Try to correct that or press 'restart' to restart.");
$default_feedbacktext     = sprintf( _("The algorithm for finding errors in this quiz is a quite simple one. If you feel the message doesn't make any sense, please post a feedback message in <a %s>this forum topic</a>."), "href='http://www.pgdp.net/phpBB2/viewtopic.php?t=TID' target='_blank'");





?>
