<?php

$qt_differencehead        = _('Difference with expected text');
$qt_difference            = _('There is still a difference between your text and the expected one.');
$qt_blanklines            = _('There are probably too few or too many blank lines before this text:');
$qt_unknown               = _('Finding the reason for this is beyond the current scope of the analysing software.');
$qt_frstdiff              = _('This is the first differing line:');

// vim: sw=4 ts=4 expandtab
