<?PHP

$default_hintlink         = 'Desperate? Can\'t find it?';
$default_challenge        = 'Try to correct that or press \'restart\' to restart.';
$default_feedbacktext     = 'The algorithm for finding errors in this quiz is a quite simple one. If you feel the message doesn\'t make any sense, please post a feedback message in <a href=\'http://www.pgdp.net/phpBB2/viewtopic.php?t=9165\' target=\'_blank\'>this forum topic</a>.';





?>