#!/bin/sh

# Compare the db-schema of the current installation
# to the db-schema you get by taking an installation of the previous release
# and applying all upgrade-scripts in the current/in-progress release.
#
# (Do the upgrade-scripts accurately reflect all the necessary changes,
# or did we sneak a db-schema change into the current installation,
# and are perhaps now depending on it?)

prev_tag=R200510
curr_tag=production
upgrade_number=07

setup_dir=`dirname $0`
testing_dir=/tmp/dp_schema_check
testing_code_dir=$testing_dir/c
testing_db_name=temp_dp_schema_check

php_cli_exec='<<PHP_CLI_EXECUTABLE>>'

mkdir $testing_dir

echo ""
echo "Dumping the schema of the current database..."
$setup_dir/dump_db_schema --table-list-from-code > $testing_dir/current_schema_dump
# Use --table-list-from-code because a real DP database will typically have
# a) a full complement of phpbb tables, and
# b) some adhoc tables,
# neither of which are pertinent to this check.

echo ""
echo "Creating a config file for a test install..."
echo "
    TAG=$curr_tag
    GROUP=$USER
    SHIFT_TO_LIVE=yes

    _CODE_DIR=$testing_code_dir
    _DB_NAME=$testing_db_name
    _DB_SERVER=<<DB_SERVER>>
    _DB_USER=<<DB_USER>>
    _DB_PASSWORD='<<DB_PASSWORD>>'

    # Need to set the booleans, otherwise site_vars.php will raise syntax errors.
    _TESTING=TRUE
    _USE_PHP_SESSIONS=TRUE
    _MAINTENANCE=FALSE
    _METADATA=TRUE
    _CORRECTIONS=TRUE
    _WRITEBIGTABLE=TRUE
    _READBIGTABLE=TRUE
    _AUTO_POST_TO_PROJECT_TOPIC=FALSE

    # For update_phpbb_posts_text.php
    _FORUMS_PROJECT_WAITING_IDX=99
    _FORUMS_PROJECT_AVAIL_IDX=99
    _FORUMS_PROJECT_PP_IDX=99
    _FORUMS_PROJECT_POSTED_IDX=99
" > $testing_dir/config.sh

echo "Getting a test copy of the '$curr_tag' code..."
$setup_dir/update_from_cvs $testing_dir/config.sh

echo ""
cd $testing_code_dir/SETUP

echo ""
echo "Getting db_schema.sql from the previous release..."
cvs_server=dproofreaders.cvs.sourceforge.net
cvs_account=:pserver:anonymous@$cvs_server
cvs -d$cvs_account:/cvsroot/dproofreaders get -p -r $prev_tag dp-devel/SETUP/db_schema.sql > ./db_schema.sql

echo ""
echo "Creating and/or cleaning out the test database..."
mysql -h <<DB_SERVER>> -u <<DB_USER>> -p'<<DB_PASSWORD>>' -e "DROP   DATABASE $testing_db_name"
mysql -h <<DB_SERVER>> -u <<DB_USER>> -p'<<DB_PASSWORD>>' -e "CREATE DATABASE $testing_db_name"
if [ $? != 0 ]; then
    echo "CREATE DATABASE failed."
    echo "Probably some sufficiently powerful MySQL user will have to invoke:"
    echo "    GRANT ALL ON $testing_db_name.* TO <<DB_USER>>@<<DB_SERVER>> IDENTIFIED BY '<<DB_PASSWORD>>'"
    exit 1
fi

echo ""
echo "Running install_db.php to set up test db..."
$php_cli_exec ./install_db.php

echo ""
echo "Applying all upgrade scripts..."
cd $testing_code_dir/SETUP/upgrade/$upgrade_number
for f in *.php; do
    echo ""
    echo "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
    echo $f
    echo ""
    $php_cli_exec $f
done
echo ""
echo "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
cd $testing_code_dir/SETUP

echo ""
echo "Dumping the schema of the resulting database..."
if [ -e $testing_dir/upgraded_schema_dump ]; then
    mv $testing_dir/upgraded_schema_dump $testing_dir/upgraded_schema_dump.bak
fi
./dump_db_schema --table-list-from-db > $testing_dir/upgraded_schema_dump

echo ""
echo "Comparing the two schemas..."
vim -d $testing_dir/current_schema_dump $testing_dir/upgraded_schema_dump

echo ""
echo "When you're done, don't forget to..."
echo "    rm -rf $testing_dir"
echo "    DROP DATABASE $testing_db_name;"

# vim: sw=4 ts=4 expandtab
