# $Id$
# MySQL DDL script for alterations to migrate to the modified schema of January 2005.

# change unique index on projectid to primary key
ALTER TABLE page_counts DROP INDEX projectid;
ALTER TABLE page_counts ADD PRIMARY KEY (projectid);

# replace the table project_pages with table pages
DROP TABLE project_pages;
# this was generated by MySQL
CREATE TABLE pages (
`pageId` int( 11 ) NOT NULL AUTO_INCREMENT ,
`projectid` varchar( 25 ) NOT NULL default '',
`pageCode` varchar( 20 ) NOT NULL default '',
`origPageCode` varchar( 20 ) ,
`stateCode` varchar( 50 ) NOT NULL default '',
`insertTime` int( 20 ) NOT NULL,
`metadata` set( 'frontmatter', 'backmatter', 'division', 'verse',
'poetry', 'letter', 'toc', 'footnote', 'sidenote', 'epigraph', 'table',
'list', 'math', 'drawing', 'badscan', 'blank', 'illustration', 'missing',
'drawing' ),
PRIMARY KEY ( `pageId` ) ,
UNIQUE KEY `alternatekey` ( `projectid` , `pageCode` )
) TYPE = MYISAM  DEFAULT CHARSET=latin1;

# add new table pageTasks
CREATE TABLE `pageTasks` (
`pageTaskId` int( 20 ) NOT NULL AUTO_INCREMENT ,
`pageId` int( 20 ) NOT NULL default '0',
`sequenceNumber` int( 8 ) NOT NULL default '1',
`taskCode` varchar( 64 ) NOT NULL default '',
`userName` varchar( 25 ) default NULL ,
`checkoutTime` int( 20 ) default NULL ,
`saveTempTime` int( 20 ) default NULL ,
`saveCompleteTime` int( 20 ) default NULL ,
`turnBackTime` int( 20 ) default NULL ,
`taskStateCode` enum( 'AVAILABLE', 'CHECKED_OUT', 'COMPLETED', 'ON_HOLD' ) NOT NULL default 'AVAILABLE',
PRIMARY KEY ( `pageTaskId` ) ,
KEY `userName` ( `userName` ) ,
KEY `pageId` ( `pageId` )
) TYPE = MYISAM  DEFAULT CHARSET=latin1;

# change checkedoutby column in table projects from "text" to  "varchar"
ALTER TABLE projects CHANGE checkedoutby checkedoutby VARCHAR( 25 );
# add several indexes to table projects
ALTER TABLE projects ADD INDEX (username);
ALTER TABLE projects ADD INDEX (checkedoutby);
ALTER TABLE projects ADD INDEX (postproofer);

# convert task_id index on table Tasks to primary key
# must add new index on task_id before dropping old one.
ALTER TABLE tasks ADD PRIMARY KEY (task_id);
ALTER TABLE tasks DROP INDEX task_id;

# remove redundant non-primary key on username
ALTER TABLE users DROP INDEX username;

# Add surrogate primary key to table usersettings
# and add index in username (could add setting to index, but it is just overhead -
# username gets close enough.
ALTER TABLE `usersettings` ADD `usersettingsid` INT( 20 ) NOT NULL AUTO_INCREMENT PRIMARY KEY FIRST ;
ALTER TABLE usersettings ADD INDEX (username);
