<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Frameset//EN" 
"http://www.w3.org/TR/html4/frameset.dtd">
<html><head><title>Proofing Interface</title></head><frameset 
rows="*,73"><frame 
name="proofframe" src="<?PHP
  echo "projects.php{$frameGet}";
?>" marginwidth="2" marginheight="2" frameborder="0"><frame 
name="menuframe" src="ctrl_frame.php" marginwidth="2" marginheight="2" frameborder="0"></frameset><noframes>Your 
browser is not frames capable!</noframes></html>