<FONT SIZE="-1"><INPUT 
TYPE="text" VALUE="" name="markBox" size="10" onclick="this.select()"> | <a 
href="#" onclick="iMU(3)" title="[Sidenote:">[Sidenote: </a>&nbsp;| <a 
href="#" onclick="iMUe(3)" title="]">]</a> | <a 
href="#" onclick="iMU(1)" title="[Illustration:">[Illustration: </a>&nbsp;| <a 
href="#" onclick="iMUe(1)" title="]">]</a> | <a 
href="#" onclick="iMU(7)" title="&lt;i&gt;">&lt;i&gt;</a> | <a 
href="#" onclick="iMUe(7)" title="&lt;/i&gt;">&lt;/i&gt;</a> | <a 
href="#" onclick="iMUe(0)" title="*">*</a> | <a 
href="#" onclick="iMU(2)" title="[Footnote:">[Footnote: </a>&nbsp;| <a 
href="#" onclick="iMUe(2)" title="]">]</a> | <a 
href="#" onclick="iMU(5)" title="/*">/*</a> | <a 
href="#" onclick="iMUe(5)" title="*/">*/</a> | <a 
href="#" onclick="iMU(4)" title="*  *  *  *  *">*&nbsp;&nbsp;*&nbsp;&nbsp;*&nbsp;&nbsp;*&nbsp;&nbsp;*</a> | <a 
href="#" onclick="iMU(6)" title="[Blank Page]">[Blank Page]</a>