<FONT SIZE="-1"><a
href="#" onclick="iMUO(2)" title="[Sidenote:">[Sidenote: </a>&nbsp;| <a
href="#" onclick="iMUO(22)" title="]">]</a> | <a
href="#" onclick="iMUO(3)" title="[Illustration:">[Illustration: </a>&nbsp;| <a
href="#" onclick="iMUO(23)" title="]">]</a> | <a
href="#" onclick="iMUO(0)" title="*">*</a> | <a
href="#" onclick="iMUO(1)" title="[Footnote #:">[Footnote #: </a>&nbsp;| <a
href="#" onclick="iMUO(21)" title="]">]</a> | <a
href="#" onclick="iMUO(4)" title="<? echo _("Start poetry/table"); ?>">/*</a> | <a
href="#" onclick="iMUO(24)" title="<? echo _("End poetry/table"); ?>">*/</a> | <a
href="#" onclick="iMUO(7)" title="<? echo _("Start block quote"); ?>">/#</a> | <a
href="#" onclick="iMUO(27)" title="<? echo _("End block quote"); ?>">#/</a> | <a
href="#" onclick="iMUO(5)" title="*  *  *  *  *">*&nbsp;&nbsp;*&nbsp;&nbsp;*&nbsp;&nbsp;*&nbsp;&nbsp;*</a> | <a
href="#" onclick="iMUO(6)" title="[Blank Page]">[Blank Page]</a>
