<?php
/* The use of HTML numeric entities in these strings assumes that they will
 * only be used when outputing HTML or XML. Until the assumptions in the
 * current codebase about ISO-Latin-1 being the standard character encoding
 * are fixed, non-ISO-Latin-1 (preferably non-ASCII) characters should not
 * be used in these strings.
 * If UTF-8 is really needed here, it could be accomodated by installing the
 * mbstrings PHP extension and using the function mb_encode_numericentity()
 * to convert the UTF-8 to entities for display on non-UTF-8 web pages.
 */
$iso_639_loc=array(
"hy"=>"&#1344;&#1377;&#1397;&#1381;&#1408;&#1381;&#1398;", // Հայերեն
"bg"=>"&#1041;&#1098;&#1083;&#1075;&#1072;&#1088;&#1089;&#1082;&#1080;", // Български
"be"=>"&#1041;&#1077;&#1083;&#1072;&#1088;&#1091;&#1089;&#1082;&#1110;", // Беларускі
"br"=>"Brezhoneg",
"ca"=>"Catal&#224;", // Català
"cy"=>"Cymraeg",
"cs"=>"&#268;e&#353;tina", // Čeština
"da"=>"Dansk",
"de"=>"Deutsch",
"et"=>"Eesti",
"el"=>"&#917;&#955;&#955;&#951;&#957;&#953;&#954;&#940;", // Ελληνικά
"en"=>"English",
"es"=>"Espa&#241;ol", // Español
"eo"=>"Esperanto",
"eu"=>"Euskara",
"fo"=>"F&#248;royskt", // Føroyskt
"fr"=>"Fran&#231;ais", // rançais
"ga"=>"Gaeilge",
"gl"=>"Galego",
"ka"=>"&#4325;&#4304;&#4320;&#4311;&#4323;&#4314;&#4312;", // ქართული
"he"=>"&#1506;&#1489;&#1512;&#1497;&#1514;", // עברית
"hr"=>"Hrvatski",
"it"=>"Italiano",
"is"=>"&#205;slenska", // Íslenska
"kl"=>"Kalaallisut",
"kw"=>"Kernowek",
"la"=>"Latina",
"lt"=>"Lietuvi&#371;", // Lietuvių
"lv"=>"Latvie&#353;u", // Latviešu
"hu"=>"Magyar",
"mk"=>"&#1052;&#1072;&#1082;&#1077;&#1076;&#1086;&#1085;&#1089;&#1082;&#1080;", // Македонски
"mt"=>"Malti",
"gv"=>"Manx",
"nl"=>"Nederlands",
"no"=>"Norsk",
"nn"=>"Nynorsk",
"pl"=>"Polski",
"pt"=>"Portugu&#234;s", // Português
"ro"=>"Rom&#226;nesc", // Românesc
"ru"=>"&#1056;&#1091;&#1089;&#1089;&#1082;&#1080;&#1081;", // Русский
"sq"=>"Shqip",
"sk"=>"Sloven&#269;ina", // Slovenčina
"sl"=>"Sloven&#353;&#269;ina", // Slovenščina
"sr"=>"&#1057;&#1088;&#1087;&#1089;&#1082;&#1080;", // Српски
"fi"=>"Suomi",
"sv"=>"Svenska",
"tr"=>"T&#252;rk&#231;e", // Türkçe
"uk"=>"&#1059;&#1082;&#1088;&#1072;&#1111;&#1085;&#1100;&#1089;&#1082;&#1072;", // Україньска
);
?>
