<?PHP
// unavailable
define("UNAVAIL_FIRST","unavail_first");
define("UNAVAIL_SECOND","unavail_second");

// bad page
define("BAD_FIRST","bad_first");
define("BAD_SECOND","bad_second");

// available
define("AVAIL_FIRST","avail_first");
define("AVAIL_SECOND","avail_second");

// checked out
define("OUT_FIRST","out_first");
define("OUT_SECOND","out_second");

// temp save
define("TEMP_FIRST","temp_first");
define("TEMP_SECOND","temp_second");

// save
define("SAVE_FIRST","save_first");
define("SAVE_SECOND","save_second");
?>