<?php
include_once($relPath.'v_resolution.inc');

$p_l= array(_("No Rounds"), _("First Round"), _("Second Round"), _("Both Rounds"));
$u_l= array(_("English"),_("French"),_("German"),_("Spanish"), _("Italian"), _("Portuguese"));
$i_r= $i_resolutions;
$f_f= array(_("Browser Default"),'Courier','Times','Arial','Lucida','Monospaced','DPCustomMono2');
$f_s= array(_("Browser Default"),'8pt','9pt','10pt','11pt','12pt','13pt','14pt','15pt','16pt','18pt','20pt');
$u_n= array('0', '2', '4', '6', '8', '10', '12', '14', '16', '18', '20');
$u_il= array(_("English"), _("Dutch"), _("French"), _("German"), _("Italian"), _("Portuguese"), _("Spanish"));
$u_iloc= array('en_EN', 'nl_NL', 'fr_FR', 'de_DE', 'it_IT', 'pt_PT', 'es_ES');
$i_pm= array(_("All Projects"), _("Active Projects"), _("Search Page"));
$i_stats = array(_("Public"), _("Anonymous"), _("Private"));
?>