<?php
include_once($relPath.'v_resolution.inc');

$p_l= array('no rounds','first round','second round','both rounds');
$u_l= array('English','French','German','Spanish', 'Italian', 'Portuguese');
$i_r= $i_resolutions;
$f_f= array('Browser Default','Courier','Times','Arial','Lucida','Monospaced','DPCustomMono2');
$f_s= array('Browser Default','8pt','9pt','10pt','11pt','12pt','13pt','14pt','15pt','16pt','18pt','20pt');
$u_n= array('0', '2', '4', '6', '8', '10', '12', '14', '16', '18', '20');
$u_il= array('English', 'Dutch', 'French', 'German', 'Italian', 'Portuguese', 'Spanish');
$u_iloc= array('en_EN', 'nl_NL', 'fr_FR', 'de_DE', 'it_IT', 'pt_PT', 'es_ES');
$i_pm= array('All Projects', 'Active Projects', 'Search Page');
$i_stats = array('Public', 'Anonymous', 'Private');
?>