<?php
// This configuration file controls which languages are installed and
// configured for this site.

// The URI under $forums_url for a specific language's forum. This will
// be included in the menu bar for users of that language. See theme.inc.
// i.e.: if the forum URL for the French team is:
//     http://www.pgdp.net/phpBB3/viewtopic.php?t=4321
// the array entry would be:
//     "fr" => "viewtopic.php?t=4321",
$lang_forum_data = [
];

// Language names in the language's native form.
// This overrides/supplements the ones provided by locale_get_display_name().
$lang_name_data = [
    "pd" => "Pennsilfaanisch Deitsch",
];

// Language names in their English form.
// This overrides/supplements the ones provided by locale_get_display_name().
$eng_name_data = [
    "pd" => "Pennsylvania Dutch",
];
