<?php
// This configuration file controls which languages are installed and
// configured for this site.

// Directory under faq/ for files that are translated in their entirety
// instead of via gettext().
// Note that this currently isn't used as-such (each language has their own
// proofreading guidelines for instance) and either needs to be
// implemented or purged.
$lang_dir_data=array(
);

// The URI under $forums_url for a specific language's forum. This will
// be included in the menu bar for users of that language. See theme.inc.
// i.e.: if the forum URL for the French team is:
//     http://www.pgdp.net/phpBB3/viewtopic.php?t=4321
// the array entry would be:
//     "fr" => "viewtopic.php?t=4321",
$lang_forum_data=array(
);

// Language names in the language's native form. This overrides the ones
// set in pinc/iso_639_loc_list.inc. Consult that file for array syntax
// and coding restrictions.
$lang_name_data=array(
);

// Language names in their English form. This overrides the ones
// set in pinc/iso_639_list.inc. Consult that file for array syntax.
$eng_name_data=array(
);

// vim: sw=4 ts=4 expandtab
