#!/bin/bash

# make_tarball <tag> <base_of_files_to_create>
# Make a tarball and zip of (a particular version of) the DP code.
# e.g.:
#     make_tarball R200406 ~/dp.R200406
#     (creates ~/dp.R200406.tgz and ~/dp.R200406.zip)

if [ $# != 2 ]; then
    echo 1>&2 "usage: make_tarball <tag> <base_of_files_to_create>"
    exit 1
fi

tag=$1
creation_base=$2

group=$USER

script_dir=`dirname $0`

tmpdir=/tmp/make_tarball.$$

if [ ! -d $tmpdir ]; then
    mkdir $tmpdir
fi
rm -rf $tmpdir/c

echo
echo "get_git_clone..."
$script_dir/get_git_clone $tag $group $tmpdir/c

echo
echo "Creating tarball..."
tar --create --gzip --file=$creation_base.tgz --directory=$tmpdir c

echo
echo "Creating zip..."
(cd $tmpdir && zip -q -r - c ) > $creation_base.zip

echo
echo "Removing snapshot..."
rm -rf $tmpdir

echo
echo "Done."

# vim: sw=4 ts=4 expandtab
