<br><br>
<table width='75%' border='4' rules='all'>
          <tr>
       <td colspan=3> <? echo _("Pages proofread by you and..."); ?></td></tr>
       <tr> <td bgcolor='#FFCC66'> <? echo _("IN PROGRESS (awaiting completion this round)"); ?></td>
            <td bgcolor='#99FF66'> <? echo _("DONE (still available for editing this round)"); ?></td>
            <td bgcolor='#FF3366'> <? echo _("DONE in a previous round (no longer available for editing)"); ?></td>
       </tr>
</table>
<br><br>
