<?php
$relPath="./../../pinc/";
include_once($relPath.'site_vars.php');
include_once($relPath.'dp_main.inc');
include_once($relPath.'project_states.inc');
include_once($relPath.'stages.inc');
include_once($relPath.'Project.inc');
include_once('./post_files.inc');
include_once($relPath.'word_checker.inc');
include_once('./word_freq_table.inc');

set_time_limit(0); // no time limit

$projectid = $_GET["projectid"];

// if format is 'text', all words and frequencies will be printed
// if format is not 'text', an HTML page is displayed
$format = @$_GET["format"];

// anything that appears in the list less than this number
// won't show up in the list
$minFreq = array_get($_GET, 'minFreq', 5);

// get the latest project text of all pages up to last possible round
$last_possible_round = get_Round_for_round_number(MAX_NUM_PAGE_EDITING_ROUNDS);
$pages_res = page_info_query($projectid,$last_possible_round->id,'LE');
$all_pages_text = join_proofed_text($projectid,$pages_res,false,false,'');

// normalize the text for processing
$all_pages_text = preg_replace("/^-+File: .*$/m",'',$all_pages_text);

$all_words_in_text = get_all_words_in_text($all_pages_text);
$all_words_w_freq = generate_frequencies($all_words_in_text);

$languages = array_unique(array_values(get_project_languages($projectid)));

$site_possible_bad_words = array();
foreach ( $languages as $language ) {
    $langcode3 = langcode3_for_langname( $language );
    $site_possible_bad_words = array_merge($site_possible_bad_words, load_site_possible_bad_words($langcode3));
}
array_unique($site_possible_bad_words);

// now, remove any words that are already on the project's bad word list
$site_possible_bad_words = array_diff($site_possible_bad_words, load_project_bad_words($projectid) );

// $site_possible_bad_words doesn't have frequency info, 
// so start with the info in $all_words_w_freq,
// and extract the items where the key matches a key in $bad_words.

$bad_words_w_freq = array_intersect_key( $all_words_w_freq, array_flip($site_possible_bad_words) );

// sort the list by frequency, then by word
array_multisort(array_values($bad_words_w_freq), SORT_DESC, array_keys($bad_words_w_freq), SORT_ASC, $bad_words_w_freq);


// if the user wants the list in text-only mode
if($format == "text") {
    # The following is a pure hack for evil IE not accepting filenames
    $filename="${projectid}_possible_bad_words.txt";
    header("Content-type: text/plain");
    header('Content-Disposition: attachment; filename="' . $filename . '"');
    header('Cache-Control: must-revalidate, post-check=0, pre-check=0');
    header('Pragma: public');

    // freq side
    foreach( $bad_words_w_freq as $word => $freq) {
        echo "$word - $freq\r\n";
    }
    exit;
}

?>
<html>
<head>
<title>Candidate words from site possible bad words</title>
</head>
<body>
<h1>Candidate words from site possible bad words</h1>
<p>The list below contains words from the site's possible bad words files that are found in this project. The list was generated by accessing the most recent text of each page and comparing it against the site bad word suggestions file for the project languages and removing words already on the project's Bad Words list.<p>

<p>By definition, words in the possible bad words file are stealth-scannos that will not be flagged by the external spell check. The existance of these words in the project does <b>not</b> mean these words are scannos, just that they might be. If you find words in the list below that should be flagged for extra attention within WordCheck, add them to the project's Bad Words List by copying them into the Bad Words box when editing the project. (Take care not to overwrite any words that are already in the box.) See also the <a href="<?=$code_url;?>/faq/spellcheck-faq.php">WordCheck FAQ</a> for more information on the new WordCheck system.</p>

<p>You can <a href="show_project_possible_bad_words.php?projectid=<?PHP echo $projectid; ?>&amp;format=text">download</a> a copy of the full word list with frequencies for offline analysis. When adding the final list to the input box on the Edit Project page, the frequencies can be left in and the system will remove them.</p>

<?
// how many instances (ie: frequency sections) are there?
$instances=1;
// what is the intial cutoff frequecny?
$initialFreq=5;
// what are the cutoff options?
$cutoffOptions = array(1,2,3,4,5,10,25,50);

echo_cutoff_script($cutoffOptions,$instances);
$cutoffString = get_cutoff_string($cutoffOptions);
?>

<p>Words that appear fewer than <b><span id="current_cutoff"><?=$initialFreq;?></span></b> times are not shown. Other cutoff options are available: <?=$cutoffString;?>.</p>
<?
if ( count($messages) > 0 )
{
    echo "<p>\n";
    echo "The following warnings/errors were raised:<br>\n";
    foreach ( $messages as $message )
    {
        echo "$message<br>\n";
    }
    echo "</p>\n";
}

printTableFrequencies($initialFreq,$cutoffOptions,$bad_words_w_freq,$instances--);

// vim: sw=4 ts=4 expandtab
?>
</body>
</html>
